---
apiVersion: v1
kind: Pod
metadata:
    name: web-pod
    labels:
        app: myapp
spec:
    containers:
        - name: mypod
          image: nginx
---
apiVersion: v1
kind: Service
metadata:
    name: nodeport-service
spec:
    type: NodePort
    selector:
        app: myapp
    ports:
        - targetPort: 80
          port: 80
          nodePort: 30200

