apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
     app: newapp
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
             matchExpressions:
             - key: app
               operator: In
               values:
               - myapp
        topologyKey: "kubernetes.io/hostname"

