apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
     app: myapp
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
       - weight: 1
         preference:
             matchExpressions:
             - key: size
               operator: In
               values:
                 - large
       - weight: 25
         preference:
             matchExpressions:
             - key: size
               operator: In
               values:
                 - medium

