apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      role: web-frontend
  template:
    metadata:
      labels:
        role: web-frontend
    spec:
      containers:
      - name: web
        image: nginx
        env:
           - name: SECRET_USERNAME
             valueFrom:
                  secretKeyRef:
                        name: mysecret
                        key: username
           - name: SECRET_PASSWORD
             valueFrom:
                  secretKeyRef:
                        name: mysecret
                        key: password

